-- Creating a DATABASE and SCHEMA
CREATE DATABASE IF NOT EXISTS RETAIL_DB;
CREATE SCHEMA IF NOT EXISTS RETAIL_DB.BRONZE_RAW;

USE DATABASE RETAIL_DB;
USE SCHEMA BRONZE_RAW;


-- Creating a FILE FORMAT for CSV FILES
CREATE OR REPLACE FILE FORMAT CSV_FF
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL');



-- Creating Storage Integration for us using the ROLE in AWS IAM
CREATE OR REPLACE STORAGE INTEGRATION RETAIL_S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '<Your Arns Key>'
  STORAGE_ALLOWED_LOCATIONS = ('<Your S3 Bucket URL>');

desc integration RETAIL_S3_INT;



-- Creating a STAGE and Uploading the raw data into it
CREATE OR REPLACE STAGE S3_RETAIL_STAGE
  STORAGE_INTEGRATION = RETAIL_S3_INT
  URL = '<Your S3 Bucket URL>'
  FILE_FORMAT = CSV_FF;

list @s3_retail_stage;


-- Creating customer Table and PIPE for AUTO Ingestion 

CREATE OR REPLACE TABLE CUSTOMER_RAW (
    C_CUSTKEY     NUMBER,
    C_NAME        STRING,
    C_ADDRESS     STRING,
    C_NATIONKEY   NUMBER,
    C_PHONE       STRING,
    C_ACCTBAL     NUMBER,
    C_MKTSEGMENT  STRING,
    C_COMMENT     STRING
);

-- ALTER PIPE PIPE_CUSTOMER_RAW REFRESH;

CREATE OR REPLACE PIPE PIPE_CUSTOMER_RAW
  AUTO_INGEST = TRUE
AS
COPY INTO CUSTOMER_RAW
FROM @S3_RETAIL_STAGE/raw_customer.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'CONTINUE';

select * from customer_raw;
-- Creating Line Item Table And Pipe

CREATE OR REPLACE TABLE LINEITEM_RAW (
    L_ORDERKEY        NUMBER,
    L_PARTKEY         NUMBER,
    L_SUPPKEY         NUMBER,
    L_LINENUMBER      NUMBER,
    L_QUANTITY        NUMBER,
    L_EXTENDEDPRICE   NUMBER,
    L_DISCOUNT        NUMBER,
    L_TAX             NUMBER,
    L_RETURNFLAG      STRING,
    L_LINESTATUS      STRING,
    L_SHIPDATE        DATE,
    L_COMMITDATE      DATE,
    L_RECEIPTDATE     DATE,
    L_SHIPINSTRUCT    STRING,
    L_SHIPMODE        STRING,
    L_COMMENT         STRING
);

-- ALTER PIPE PIPE_LINEITEM_RAW REFRESH;

CREATE OR REPLACE PIPE PIPE_LINEITEM_RAW
  AUTO_INGEST = TRUE
AS
COPY INTO LINEITEM_RAW
FROM @S3_RETAIL_STAGE/raw_lineitem.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'CONTINUE';

SELECT * FROM LINEITEM_RAW;


-- Creating Raw_nation table and Pipe

CREATE OR REPLACE TABLE NATION_RAW (
    N_NATIONKEY  NUMBER,
    N_NAME       STRING,
    N_REGIONKEY  NUMBER,
    N_COMMENT    STRING
);

-- ALTER PIPE PIPE_NATION_RAW REFRESH;
 
CREATE OR REPLACE PIPE PIPE_NATION_RAW
  AUTO_INGEST = TRUE
AS
COPY INTO NATION_RAW
FROM @S3_RETAIL_STAGE/raw_nation.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'CONTINUE';

SELECT * FROM NATION_RAW;

-- Creating Table for raw_region and Pipe

CREATE OR REPLACE TABLE REGION_RAW (
    R_REGIONKEY NUMBER,
    R_NAME      STRING,
    R_COMMENT   STRING
);

-- ALTER PIPE PIPE_REGION_RAW REFRESH;

CREATE OR REPLACE PIPE PIPE_REGION_RAW
  AUTO_INGEST = TRUE
AS
COPY INTO REGION_RAW
FROM @S3_RETAIL_STAGE/raw_region.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'CONTINUE';

SELECT * FROM REGION_RAW;


-- Creating Table for raw_orders and Pipe

CREATE OR REPLACE TABLE ORDERS_RAW (
    O_ORDERKEY      NUMBER,
    O_CUSTKEY       NUMBER,
    O_ORDERSTATUS   STRING,
    O_TOTALPRICE    NUMBER,
    O_ORDERDATE     DATE,
    O_ORDERPRIORITY STRING,
    O_CLERK         STRING,
    O_SHIPPRIORITY  NUMBER,
    O_COMMENT       STRING
);

ALTER PIPE PIPE_ORDERS_RAW REFRESH;

CREATE OR REPLACE PIPE PIPE_ORDERS_RAW
  AUTO_INGEST = TRUE
AS
COPY INTO ORDERS_RAW
FROM @S3_RETAIL_STAGE/raw_orders.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'CONTINUE';

SELECT * FROM ORDERS_RAW;


--Creating table part_raw and Pipe

CREATE OR REPLACE TABLE PART_RAW (
    P_PARTKEY      NUMBER,
    P_NAME         STRING,
    P_MFGR         STRING,
    P_BRAND        STRING,
    P_TYPE         STRING,
    P_SIZE         NUMBER,
    P_CONTAINER    STRING,
    P_RETAILPRICE  NUMBER,
    P_COMMENT      STRING
);

-- ALTER PIPE PIPE_PART_RAW REFRESH;

CREATE OR REPLACE PIPE PIPE_PART_RAW
  AUTO_INGEST = TRUE
AS
COPY INTO PART_RAW
FROM @S3_RETAIL_STAGE/raw_part.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'CONTINUE';

SELECT * FROM PART_RAW;


--Creating table partsupp_raw and Pipe

CREATE OR REPLACE TABLE PARTSUPP_RAW (
    PS_PARTKEY     NUMBER,
    PS_SUPPKEY     NUMBER,
    PS_AVAILQTY    NUMBER,
    PS_SUPPLYCOST  NUMBER,
    PS_COMMENT     STRING
);

-- ALTER PIPE PIPE_PARTSUPP_RAW REFRESH;

CREATE OR REPLACE PIPE PIPE_PARTSUPP_RAW
  AUTO_INGEST = TRUE
AS
COPY INTO PARTSUPP_RAW
FROM @S3_RETAIL_STAGE/raw_partsupp.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'CONTINUE';

SELECT * FROM PARTSUPP_RAW;


-- Creating raw Supplier table and Pipe 

CREATE OR REPLACE TABLE SUPPLIER_RAW (
    S_SUPPKEY   NUMBER,
    S_NAME      STRING,
    S_ADDRESS   STRING,
    S_NATIONKEY NUMBER,
    S_PHONE     STRING,
    S_ACCTBAL   NUMBER,
    S_COMMENT   STRING
);

-- ALTER PIPE PIPE_SUPPLIER_RAW REFRESH;

CREATE OR REPLACE PIPE PIPE_SUPPLIER_RAW
  AUTO_INGEST = TRUE
AS
COPY INTO SUPPLIER_RAW
FROM @S3_RETAIL_STAGE/raw_supplier.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'CONTINUE';

select * from supplier_raw;